In [4]:

import os
import re
import pandas as pd
from tqdm import tqdm_notebook
from flair.data import Dictionary, Sentence
from flair.embeddings import FlairEmbeddings
from flair.trainers.language_model_trainer import LanguageModelTrainer, TextCorpus

from gensim.parsing.preprocessing import strip_multiple_whitespaces
def pad_spl_char(x):
    temp = re.sub("([^A-Za-z0-9])", r" \1 ", x)
    temp = strip_multiple_whitespaces(temp)
    return temp

I0411 20:48:51.262615  7468 file_utils.py:38] PyTorch version 1.4.0 available.
C:\Users\Rajat\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
df = pd.read_pickle("onco_10000_trials_bs_eligi.pkl")
df2 = pd.read_pickle("onco_10000_trials_detailed_desc.pkl")

In [3]:
######## Tasks. check the difference in embedding vectors quality compared from baseline

### get baseline vectors 
### load finetuned vectors
### see character level differences

In [5]:
###### load baseline model 

In [6]:

flair_embedding_forward = FlairEmbeddings('news-forward')

In [8]:
sent = df['eligibility'].iloc[0]
# df.columns

In [10]:
sent = sent.split(";")[0]

In [11]:
sent

' - INCLUSION CRITERIA: At least one of the following: Diagnosis of breast cancer, or DCIS prior to or at 45, or ovarian cancer prior to or at age 50'

In [19]:
sentence1 = Sentence(sent)

In [20]:
flair_embedding_forward.embed(sentence1)

[Sentence: "- INCLUSION CRITERIA: At least one of the following: Diagnosis of breast cancer, or DCIS prior to or at 45, or ovarian cancer prior to or at age 50" - 29 Tokens]

In [21]:
finedtuned_flair = FlairEmbeddings(r"C:\Users\Rajat\Downloads\language_model\best-lm.pt")

In [22]:
sentence2 = Sentence(sent)

In [23]:
finedtuned_flair.embed(sentence2)

[Sentence: "- INCLUSION CRITERIA: At least one of the following: Diagnosis of breast cancer, or DCIS prior to or at 45, or ovarian cancer prior to or at age 50" - 29 Tokens]

In [28]:
for tok in sentence1:
    print (tok.embedding)
    print (tok)
    t1= tok.embedding
    break

tensor([-1.9660e-04, -1.3999e-04,  1.0776e-01,  ..., -4.3986e-05,
         1.4259e-02,  6.7923e-03], device='cuda:0')
Token: 1 -


In [29]:
for tok in sentence2:
    print (tok.embedding)
    print (tok)
    t2 = tok.embedding
    break

tensor([-3.1962e-05, -3.9483e-04,  9.7167e-02,  ..., -2.9527e-04,
         2.4974e-03,  1.4206e-02], device='cuda:0')
Token: 1 -


In [27]:
from scipy.spatial.distance import cosine

In [39]:
cosine(t1.cpu().numpy(), t2.cpu().numpy())

0.3835970163345337

In [36]:
t1

tensor([-1.9660e-04, -1.3999e-04,  1.0776e-01,  ..., -4.3986e-05,
         1.4259e-02,  6.7923e-03], device='cuda:0')

In [38]:
t1.cpu().numpy()

array([-1.9660413e-04, -1.3999079e-04,  1.0775547e-01, ...,
       -4.3986267e-05,  1.4259484e-02,  6.7922999e-03], dtype=float32)